/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.login;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Charles
 */
public class Login extends javax.swing.JFrame {

    String User;
    String Pas;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtUser2 = new javax.swing.JTextField();
        btnLogin2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnSignup4 = new javax.swing.JButton();
        txtpas = new javax.swing.JPasswordField();
        btnSignup5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        prgloading = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel6.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel5.setText("LOGIN");

        txtUser2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtUser2.setForeground(new java.awt.Color(204, 204, 204));
        txtUser2.setText("username");
        txtUser2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUser2FocusLost(evt);
            }
        });
        txtUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        btnLogin2.setBackground(new java.awt.Color(22, 95, 167));
        btnLogin2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLogin2.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin2.setText("Login");
        btnLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Not a member? ");

        btnSignup4.setForeground(java.awt.SystemColor.textHighlight);
        btnSignup4.setText("Signup");
        btnSignup4.setBorder(null);
        btnSignup4.setBorderPainted(false);
        btnSignup4.setContentAreaFilled(false);
        btnSignup4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSignup4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        txtpas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtpas.setForeground(new java.awt.Color(204, 204, 204));
        txtpas.setText("password");
        txtpas.setEchoChar('\u0000');
        txtpas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasFocusLost(evt);
            }
        });

        btnSignup5.setForeground(java.awt.SystemColor.controlShadow);
        btnSignup5.setText("Forgot password?");
        btnSignup5.setBorder(null);
        btnSignup5.setBorderPainted(false);
        btnSignup5.setContentAreaFilled(false);
        btnSignup5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSignup5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignup1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel5)
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignup5)
                    .addComponent(btnLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpas, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSignup4)))
                .addGap(33, 33, 33))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(62, 62, 62)
                .addComponent(txtUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtpas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSignup5)
                .addGap(15, 15, 15)
                .addComponent(btnLogin2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnSignup4))
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );

        prgloading.setToolTipText("");
        prgloading.setAutoscrolls(true);
        prgloading.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addComponent(prgloading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(prgloading, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignup1ActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
    Thread thread = new Thread (new Runnable() {
            public void run () {
                for (int i = 0; i <=100; i++) {
                    prgloading.setValue(i);
                    prgloading.setString("LOADING PLEASE WAIT... " + Integer.toString(i) + "%");
                    try {
                        Thread.sleep(20);
                    }
                    catch (Exception e) {
                    }
                }
    Signup signup = new Signup();
    signup.setVisible(true);
    dispose();
     }       
        });
        thread.start();
    }//GEN-LAST:event_btnSignupActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed

    }//GEN-LAST:event_txtUserActionPerformed

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
         if(txtUser2.getText().trim().toLowerCase().equals("username"))
        {
            txtUser2.setText("");
            txtUser2.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUser2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser2FocusLost
           if(txtUser2.getText().trim().equals("") || 
           txtUser2.getText().trim().toLowerCase().equals("username"))
        {
            txtUser2.setText("username");
            txtUser2.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_txtUser2FocusLost

    private void txtpasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasFocusGained
        String pass = String.valueOf(txtpas.getPassword());
        if (txtpas.getText().equals("password")){
        if(pass.trim().toLowerCase().equals("password"))
        {
            txtpas.setText(null);
            txtpas.setForeground(Color.black);
            txtpas.setEchoChar('*');
        }
        }
    }//GEN-LAST:event_txtpasFocusGained

    private void txtpasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasFocusLost
        String pass = String.valueOf(txtpas.getPassword());
        if (txtpas.getText().length()==0){
        if(pass.trim().equals("") || 
           pass.trim().toLowerCase().equals("password"))
        {
            txtpas.setText("password");
            txtpas.setEchoChar('\u0000');
            txtpas.setForeground(new Color(204,204,204));
        }
        }
    }//GEN-LAST:event_txtpasFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin2ActionPerformed
    String Username = txtUser2.getText();
    String Password = new String (txtpas.getPassword());
        Thread thread = new Thread (new Runnable() {
            public void run () {
                for (int i = 0; i <=100; i++) {
                    prgloading.setValue(i);
                    prgloading.setString("LOADING PLEASE WAIT... " + Integer.toString(i) + "%");
                    try {
                        Thread.sleep(20);
                    }
                    catch (Exception e) {
                    }
                }
                if (Username.trim().toLowerCase().equals(User) &&
                    (Password.trim().toLowerCase().equals(Password))){
                    MenuForm success = new MenuForm();
                    success.setVisible(true);
                    success.pack();
                    success.setLocationRelativeTo(null);
                    dispose();
                }
                else if (Username.trim().toLowerCase().equals(User) ||
                        (Password.trim().toLowerCase().equals(Pas))){
                    JOptionPane.showMessageDialog(null, ("Please Input your Username and Password"));
                }
                else if ((!Username.trim().toLowerCase().equals(User)) || (!Password.trim().toLowerCase().equals(Pas))){
                    JOptionPane.showMessageDialog(null, ("The Username or Password is Wrong"));
                }
            }       
        });
        thread.start();
    }//GEN-LAST:event_btnLogin2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin2;
    private javax.swing.JButton btnSignup4;
    private javax.swing.JButton btnSignup5;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar prgloading;
    private javax.swing.JTextField txtUser2;
    private javax.swing.JPasswordField txtpas;
    // End of variables declaration//GEN-END:variables

    private void Close() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
