import java.awt.event.*;
import java.util.*;
import javax.swing.JOptionPane;
public class Hangman extends javax.swing.JFrame {

    private int wrongGuesses;
    private String currentWord;
    private Set<Character> guessedLetters;
    
    public Hangman() {
        initComponents();
        startNewGame();
    }

    private void startNewGame() {
        // Initialize the game variables
        wrongGuesses = 0;
        guessedLetters = new HashSet<Character>();
        currentWord = "";
        String[] words = {"ARCHAEOPTERYX", "RENDEZVOUZ", "CAFETERIA", "PHILIPPINES", "MALISCIOUS","HALLUCINATION", "MISSISSIPPI", "DESOLATE", "BADLANDS", "WASTELAND", "DESOLATE", "ABNEGATE", "DEVASTATION", "UNINHABITED"};
        currentWord = words[(int) (Math.random() * words.length)];
        // Update the display with underscores for the unknown letters
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < currentWord.length(); i++) {
            sb.append("_ ");
        }
        lblGuess.setText(sb.toString());
        lblGuess.setHorizontalAlignment(lblGuess.CENTER);
        // Clear any previously displayed hangman images
        clearHangmanImages();
    }
    
    private void clearHangmanImages() {
        // Hide all the hangman images
        HANGMAN_1.setVisible(false);
        HANGMAN_2.setVisible(false);
        HANGMAN_3.setVisible(false);
        HANGMAN_4.setVisible(false);
        HANGMAN_5.setVisible(false);
        HANGMAN_6.setVisible(false);
        HANGMAN_7.setVisible(false);
        HANGMAN_8.setVisible(false);
        HANGMAN_9.setVisible(false);
    }
    
    private void showHangmanImage(int imageNumber) {
        // Hide all the hangman images first
        clearHangmanImages();
        // Show the requested image
        switch (imageNumber) {
            case 1:
                HANGMAN_1.setVisible(true);
                break;
            case 2:
                HANGMAN_2.setVisible(true);
                break;
            case 3:
                HANGMAN_3.setVisible(true);
                break;
            case 4:
                HANGMAN_4.setVisible(true);
                break;
            case 5:
                HANGMAN_5.setVisible(true);
                break;
            case 6:
                HANGMAN_6.setVisible(true);
                break;
            case 7:
                HANGMAN_7.setVisible(true);
                break;
            case 8:
                HANGMAN_8.setVisible(true);
                break;
            case 9:
                HANGMAN_9.setVisible(true);
                break;
        }
    }
    
    private void updateGuessLabel() {
        // Update the guess label with the correctly guessed letters
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < currentWord.length(); i++) {
            char c = currentWord.charAt(i);
            if (guessedLetters.contains(c)) {
                sb.append(c);
            } else {
                sb.append("_ ");
            }
        }
        lblGuess.setText(sb.toString());
    }
    
    private void checkForGameOver() {
        if (wrongGuesses >= 9) {
            JOptionPane.showMessageDialog(this, "Game over! You lost. The word was \"" + currentWord + "\"");
            startNewGame();
        } else if (!lblGuess.getText().contains("_")) {
            JOptionPane.showMessageDialog(this, "Congratulations! You won.");
            startNewGame();
        }
    }
    
    private void guessLetter(char c) {
    // Check if the letter has already been guessed
    if (guessedLetters.contains(c)) {
        JOptionPane.showMessageDialog(this, "You already guessed that letter.");
        return;
    }
    // Add the guessed letter to the set
    guessedLetters.add(c);
    // Check if the guessed letter is in the word
    if (currentWord.indexOf(c) >= 0) {
        updateGuessLabel();
    } else {
        // The guessed letter is not in the word
        wrongGuesses++;
        showHangmanImage(wrongGuesses);
    }
    // Check for game over
    checkForGameOver();
    }





    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLetter = new javax.swing.JTextField();
        lblGuess = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        HANGMAN_9 = new javax.swing.JLabel();
        HANGMAN_8 = new javax.swing.JLabel();
        HANGMAN_7 = new javax.swing.JLabel();
        HANGMAN_6 = new javax.swing.JLabel();
        HANGMAN_5 = new javax.swing.JLabel();
        HANGMAN_4 = new javax.swing.JLabel();
        HANGMAN_3 = new javax.swing.JLabel();
        HANGMAN_2 = new javax.swing.JLabel();
        HANGMAN_1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(40, 0, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 10, 700));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("ENTER YOUR LETTER HERE...");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        txtLetter.setBackground(new java.awt.Color(255, 255, 255));
        txtLetter.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtLetter.setForeground(new java.awt.Color(102, 0, 0));
        txtLetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLetterActionPerformed(evt);
            }
        });
        getContentPane().add(txtLetter, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 80, -1));

        lblGuess.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblGuess.setForeground(new java.awt.Color(102, 0, 0));
        lblGuess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuess.setText("TEXT");
        getContentPane().add(lblGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setText("OK");
        jButton1.setActionCommand("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        HANGMAN_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HANGMAN_80.png"))); // NOI18N
        getContentPane().add(HANGMAN_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, -1));

        HANGMAN_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HANGMAN_70.png"))); // NOI18N
        getContentPane().add(HANGMAN_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, -1));

        HANGMAN_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HANGMAN_60.png"))); // NOI18N
        getContentPane().add(HANGMAN_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 360, -1));

        HANGMAN_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HANGMAN_50.png"))); // NOI18N
        getContentPane().add(HANGMAN_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, -1));

        HANGMAN_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HANGMAN_40.png"))); // NOI18N
        getContentPane().add(HANGMAN_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, -1));

        HANGMAN_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HANGMAN_30.png"))); // NOI18N
        getContentPane().add(HANGMAN_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, -1));

        HANGMAN_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HANGMAN_20.png"))); // NOI18N
        getContentPane().add(HANGMAN_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        HANGMAN_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HANGMAN_10.png"))); // NOI18N
        getContentPane().add(HANGMAN_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        HANGMAN_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HANGMAN00.png"))); // NOI18N
        getContentPane().add(HANGMAN_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BG0.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(40, 0, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLetterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String letter = txtLetter.getText().toUpperCase();
        if (letter.length() != 1) {
            JOptionPane.showMessageDialog(Hangman.this, "Please enter a single letter.");
            return;
        }
        char c = letter.charAt(0);
        if (Character.isLetter(c)) {
            guessLetter(c);
        } else {
            JOptionPane.showMessageDialog(Hangman.this, "Please enter a letter.");
        }
        // Clear the text field after each guess
        txtLetter.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hangman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hangman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HANGMAN_1;
    private javax.swing.JLabel HANGMAN_2;
    private javax.swing.JLabel HANGMAN_3;
    private javax.swing.JLabel HANGMAN_4;
    private javax.swing.JLabel HANGMAN_5;
    private javax.swing.JLabel HANGMAN_6;
    private javax.swing.JLabel HANGMAN_7;
    private javax.swing.JLabel HANGMAN_8;
    private javax.swing.JLabel HANGMAN_9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGuess;
    private javax.swing.JTextField txtLetter;
    // End of variables declaration//GEN-END:variables
}
